### ISSUE TITLE
zipped folder causes an error in uploading

### ISSUE THREAD

**Issue by klurie** [cloudOCT/cloudOCT#103]
Here is the bug report:
https://drive.google.com/file/d/0B2N2FqD1CTVXNC00WGRiTlFFM0E/view?usp=sharing

Was able to zip the files on my mac and able to upload. 

Am following up with Lian to (1) whether he was able to upload my zip file (2) getting access to his zip file

**Comment by bmistree** [comment]
Fixed by 6f806.  See commit comment.
