### ISSUE TITLE
Improve display of upvotes

### ISSUE THREAD

**Issue by bmistree** [cloudOCT/cloudOCT#125]
Currently, the number of upvotes a folder receives gets displayed to the left of its name on the main page.  This is pretty unintuitive: it's just a floating number and random arrows.

Kristen is going to determine a more sensible display for it, and ask Behram to implement it.

**Comment by klurie** [comment]
Delete contribution button should be right justified. Upvotes should come after "Contribution Information" string. See quora for approximate display. When user has not upvoted button should say [Upvote | #votes] w/ light gray background and blue writing. When user has upvoted, it should say [Upvoted | #votes] in dark gray text w/ light gray background. should also add question mark to link to FAQ.

**Comment by bmistree** [comment]
Should be fixed by commit 03b49.
