### ISSUE TITLE
contribution information is displayed as empty

### ISSUE THREAD

**Issue by klurie** [cloudOCT/cloudOCT#132]
Added contribution details and then uploaded files. After uploaded contribution appears blank and no edits appear. Only ability to delete contribution.

This was with telesto_flora_dataset (id=80) (zip file now uploaded and readme.md). Moved to a new contribution with same content so you can see the files.

**Comment by klurie** [comment]
This occurs after copying formatted markdown output...e.g. see below for an example of what didn't work.

**Telesto Flora Dataset**

A collection of 74 OCT volumes (raw and processed) from 12 different flora (e.g., plants, vegetables, fruits) collected with ThorLabs Telesto OCT system

**Files**
- **example_png**: Example B-scans representative of the samples and image quality are stored on CloudOCT.
- **volume data**: Volume data are stored in two formats at this offsite location [http://sbo-serv.stanford.edu/CloudOCT_Contributions/telesto_flora_dataset/](http://sbo-serv.stanford.edu/CloudOCT_Contributions/telesto_flora_dataset/)
  -  **.cvol** is an open source format that stores a complex-valued b-scans. cvol files can be loaded and processed using the [Telesto Processing Code Contribution on CloudOCT](https://cloudoct.com/real/show_root_folder/?folder_id=1). _Currently cvol files can be provided upon request._
  - **.raw**: Interferometric data colllected in the Thorlab's proprietary .raw format. Data can be opened in this format only with Thorlabs' software. With the Thorlabs' software, raw files can be loaded and processed using the [Telesto Processing Code Contribution on CloudOCT](https://cloudoct.com/real/show_root_folder/?folder_id=1). 

**Sample information**

All volumes are of dimensions 256 x 256 x 512  (1.285 x 1.285 x 2.57 mm^3)

Datasets include samples of apples, broccoli, cabbage, chia seeds, flower petals, lens paper, onions, oranges, peppers, raisins, spinach, and tomatoes.

**Contact**

Kristen Lurie, klurie@stanford.edu

Stanford Biomedical Optics, sbogroup.stanford@gmail.com

**Comment by klurie** [comment]
recommendation:just tell people to include readme files....

**Comment by bmistree** [comment]
Should be fixed by 5878.  The big problem had been that href's quotes weren't being escaped before being passed into javascript.  I instead put the text in a hidden div, and just copied the innerhtml over into the function that we use to display details.  This automatically handles the problem of double-escaping quotes for us.  (The next commit also adds a custom template filter to make it safe.)
