### ISSUE TITLE
Create nice way for users to indicate a pointer to their data/code that is being stored at another location

### ISSUE THREAD

**Issue by klurie** [cloudOCT/cloudOCT#84]
Do you think it would make sense for people to make "contributions" to Cloud that could be pointers to already existing online datasets? That way we don't have to actually store it but we can ways for people to still contribute even if they have their own datasets online already… what do you think? Could also be a decent strategy to encourage people who are already putting data online to have another way for it to be visible to the community.

**Comment by bmistree** [comment]
I think that this was started with offsite link.

**Comment by bmistree** [comment]
It was the offsite stuff.
