### ISSUE TITLE
File extensions for single file uploads may not be consistent with uploaded file

### ISSUE THREAD

**Issue by klurie** [cloudOCT/cloudOCT#92]
Either remove box where user can name his own file (just assume the filename is the filename they want on the site).

OR

Make it so that extension of the uploaded file matches the extension of the eventual filename. (If this doesn't happen, the file that gets downloaded will be difficult to open as it might have no extension / wrong extension)

**Comment by bmistree** [comment]
Should be fixed by ec061bed.  Went with the first specified option (removing the box where user can name the file him/herself).
