### ISSUE TITLE
Carriage returns when creating new contributions cause errors

### ISSUE THREAD

**Issue by klurie** [cloudOCT/cloudOCT#95]
Carriage returns in any field on new contribution error causes an issue. 
Carriage returns can be added in "edit" field later.

Issue is as follows:
- See data in the  main database
- Contribution page appears mostly blank to both owner and users
- Owner is unable to edit page

**Comment by klurie** [comment]
Actually, carriage returns also cause an issue when adding them when editing contribution. 

Don't have carriage returns ever!~

**Comment by bmistree** [comment]
Should be fixed: problem had been that templating engine put newlines directly into js quotes.
